title: BeOff
description: Blog cá nhân nhỏ nhỏ về học web và những điều tôi tò mò
url: "https://nguyenle-commits.github.io"
baseurl: "/nguyenlee-blog"

markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-sitemap